ignoredBuiltDependencies:
  - '@tensorflow/tfjs-node'
  - canvas
  - core-js
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tensorflow/tfjs-node'
  - bcrypt
  - canvas
  - esbuild
  - prisma
